spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:file:./data/getajob_v2;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
app.jwt-secret=NDQ0ZjZkNDk1N2E1NzEyNTQ4NmY2MTQ3NTQzZjRiMzU1NjY2NTM2OTcwN2E1MzM0NTM0Zjc4NjQzMjQ2NTQzMg==
app.jwt-expiration-milliseconds=86400000

# Email Configuration (Dev SMTP / Real SMTP)
# For Gmail: smtp.gmail.com, Port: 587
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=getajobmails@gmail.com
spring.mail.password=bqow oggy fnyi pfmt 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


spring.main.allow-bean-definition-overriding=true
